// Indian States and Union Territories
export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  // Union Territories
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

// Popular Medical Institutes in India (MBBS)
export const MBBS_INSTITUTES = [
  'All India Institute of Medical Sciences (AIIMS), New Delhi',
  'Christian Medical College (CMC), Vellore',
  'Armed Forces Medical College (AFMC), Pune',
  'Maulana Azad Medical College (MAMC), New Delhi',
  'King George\'s Medical University (KGMU), Lucknow',
  'Grant Medical College, Mumbai',
  'Seth GS Medical College, Mumbai',
  'Kasturba Medical College, Manipal',
  'Institute of Medical Sciences, BHU, Varanasi',
  'Jawaharlal Institute of Postgraduate Medical Education and Research (JIPMER), Puducherry',
  'Lady Hardinge Medical College, New Delhi',
  'Madras Medical College, Chennai',
  'Stanley Medical College, Chennai',
  'Government Medical College, Chandigarh',
  'B.J. Medical College, Ahmedabad',
  'Bangalore Medical College and Research Institute',
  'St. John\'s Medical College, Bangalore',
  'Osmania Medical College, Hyderabad',
  'Gandhi Medical College, Hyderabad',
  'Medical College Kolkata',
  'PGIMER, Chandigarh',
  'SMS Medical College, Jaipur',
  'Government Medical College, Thiruvananthapuram',
  'Government Medical College, Kozhikode',
  'Pt. B.D. Sharma University of Health Sciences, Rohtak',
  'Vardhman Mahavir Medical College, New Delhi',
  'University College of Medical Sciences, Delhi',
  'Other',
];

// Popular Medical Institutes for MD/Post-graduation
export const MD_INSTITUTES = [
  'All India Institute of Medical Sciences (AIIMS), New Delhi',
  'PGIMER, Chandigarh',
  'Christian Medical College (CMC), Vellore',
  'JIPMER, Puducherry',
  'Sanjay Gandhi Postgraduate Institute of Medical Sciences (SGPGIMS), Lucknow',
  'National Institute of Mental Health and Neurosciences (NIMHANS), Bangalore',
  'Tata Memorial Hospital, Mumbai',
  'King George\'s Medical University (KGMU), Lucknow',
  'Institute of Medical Sciences, BHU, Varanasi',
  'Maulana Azad Medical College (MAMC), New Delhi',
  'Grant Medical College, Mumbai',
  'Seth GS Medical College, Mumbai',
  'Kasturba Medical College, Manipal',
  'Lady Hardinge Medical College, New Delhi',
  'Madras Medical College, Chennai',
  'Bangalore Medical College and Research Institute',
  'St. John\'s Medical College, Bangalore',
  'Government Medical College, Chandigarh',
  'Osmania Medical College, Hyderabad',
  'Medical College Kolkata',
  'Lokmanya Tilak Municipal Medical College, Mumbai',
  'KEM Hospital, Mumbai',
  'Armed Forces Medical College (AFMC), Pune',
  'Sri Ramachandra Medical College, Chennai',
  'Amrita Institute of Medical Sciences, Kochi',
  'Other',
];
